version: "3.9"

services:
  ci-cd-app:
    image: dilkhush9060/ci-cd-pipelines:latest
    ports:
      - "5000" # internal port only, Caddy will handle external
    deploy:
      replicas: 2
      restart_policy:
        condition: any
    secrets:
      - dockerhub_credentials
    networks:
      - web

  caddy:
    image: caddy:alpine
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - web
    depends_on:
      - ci-cd-app

secrets:
  dockerhub_credentials:
    external: true

volumes:
  caddy_data:
  caddy_config:

networks:
  web:
    driver: overlay
